### ISSUE TITLE
IDs aren't 1e7d:307a

### ISSUE THREAD

**Issue by w1nk1** [duncanthrax/roccat-vulcan#1]
hi my ID is different:
ID 1e7d:3098 ROCCAT
Using a ROCCAT Vulcan 120 AIMO

**Comment by duncanthrax** [comment]
OK, I'll add that ID set. Thanks!

**Comment by duncanthrax** [comment]
Added. Please check if it works for you.

I have a 100 and just assumed the 120 would be the same except for the wrist bar. Or maybe there are different product IDs for layout variants. I have german layout.

**Comment by w1nk1** [comment]
Thank you, its working!!! <3
I am using a German layout as well, so dunno if its different for others...

Anything I can do to change the brightness of the keys myself or is it all hard coded? (sorry I am not into programming a lot otherwise I would reed your code :D)

**Comment by duncanthrax** [comment]
I've added some docs on colors to the README.md :)
