### ISSUE TITLE
The base color with the index 0 is extreme dark

### ISSUE THREAD

**Issue by rako233** [duncanthrax/roccat-vulcan#10]
I have an updated Roccat keyboard and everything is working so far, but the base color for the option -c results in low intensity lighting, even with the value of 255. I wish a lighter base color

**Comment by duncanthrax** [comment]
You are right, I tested with latest FW (1.29), and the brightness isn't on max with RGB at ff/ff/ff. I think I need different initialization settings. I can't fix it this week, since I'm out of town for a few days.

**Comment by duncanthrax** [comment]
I actually outsmarted myself on this, nothing to do with init settings. It was just a bug in my FX code. I thought that the "brightness" setting in Swarm is an additional tweak to the RGB values. I made sure it isn't.
