### ISSUE TITLE
runs only as root

### ISSUE THREAD

**Issue by w1nk1** [duncanthrax/roccat-vulcan#2]
Hi
cannot run it as normal user.

$ roccat-vulcan -v
open_device(1e7d, 3098): Unable to open HID devices 0001:0006:01 and/or 0001:0006:03

Tried to re-plug, reboot and reload udev but remains the same.
User is part of the group plugdev.

**Comment by duncanthrax** [comment]
I forgot to add the udev rule for the 120. Now fixed. Please update and try again :)

**Comment by w1nk1** [comment]
Thanks mate, all working now! :)
