### ISSUE TITLE
Add support for Ubuntu 20.04

### ISSUE THREAD

**Issue by gmale** [duncanthrax/roccat-vulcan#22]
Running the command:
```
sudo add-apt-repository ppa:duncanthrax/roccat-vulcan  
```
Results in the error:
```
E: The repository 'http://ppa.launchpad.net/duncanthrax/roccat-vulcan/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
because explicit support for 20.04 does not appear to have been added to the project. If I get more time, I can try compiling from source but others would benefit from the PPA being updated.

**Comment by gmale** [comment]
update, compiled from source and it runs but does not change the keyboard colors at all.

**Comment by gmale** [comment]
update: after switching to windows and updating all the drivers for the keyboard and fully setting it up over there, it worked when I came back to Linux (note: I had restarted linux multiple times, previously so it was not a simple issue of failing to reboot). None of the windows settings seemed to carry over but instead of the keyboard having a weird orange and red pattern, it was rainbow and when I ran `roccat-vulcan` it worked for the first time.

So this **can** work on Ubuntu. The next step is probably to update the PPA.

**Comment by gmale** [comment]
@duncanthrax thoughts?

**Comment by tux-rampage** [comment]
You don't need to configure the keyboard on windows. This is an Init-Bug that causes the program to wait forever: tux-rampage/roccat-vulcan@989ccba4fcfe970f552edc7bdae2a74785d06788

Going to prep a PR later.

**Comment by tux-rampage** [comment]
It seems to be an issue with an outdated firmware of the keyboard. This endless loop is still a bug imho, it should fail after a while.

**Comment by gmale** [comment]
Aside from the related error mentioned above, the original issue of this ticket still stands. There does not appear to be a "focal" release and the PPA should be updated, since this works on Ubuntu 20.04.

```
Err:30 http://ppa.launchpad.net/duncanthrax/roccat-vulcan/ubuntu focal Release                                                                                                                                                                                                                                                                                                   
  404  Not Found

E: The repository 'http://ppa.launchpad.net/duncanthrax/roccat-vulcan/ubuntu focal Release' does not have a Release file.
```

**Comment by duncanthrax** [comment]
Hi, I've just bumped the repo with packages for groovy, focal and bionic. Older versions discontinued. Sorry for the delay.

**Comment by gmale** [comment]
thanks!
